### ISSUE TITLE
notifications when you get a comment and a like

### ISSUE THREAD

**Issue by hongye-liang** [ucsb-cs184-f24/team12-remi#188]
- [ ] user can see notification when someone liked their post in format: "xxx put a like on your yyy"
- [ ] user can see notification when someone put a comment on their posts : "xxx commented on your yyy"

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implement notifications for when a user receives a like or comment on their post. This includes updating the Notifs component to display these new types of notifications alongside friend requests.

You can review changes in this commit: https://github.com/lkilu6456546/ucsb-cs184-f24-team12-remi-188/commit/02ccf5d36ffc97ecc9a9b3a3846ede76a1e4ac25.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
