### ISSUE TITLE
Make Firestore Database Diagram/ Design

### ISSUE THREAD

**Issue by SunhuChoi** [ucsb-cs184-f24/team12-remi#6]
As a developer, I want to be able to store information into a Firestore database.
Develop a database design diagram for how to store user information such as email and id, maintain a list of their friends, store posts and notifications pending for a user. This should consists of collections/subcollections that optimally organize and store the information convenient for access for developers in rendering frontend information from backend data.

**Comment by anushkavijay** [comment]
![Image](https://github.com/user-attachments/assets/5ef8e159-b6bd-4ebd-961b-228028c89c3f)
